name: Trigger Argo CD Sync

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Argo CD Sync
        run: |
          curl -k -X POST https://192.168.1.11/api/v1/applications/backend-app/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}"

